### ISSUE TITLE
Create a Guide: Data analysis tools for your project

### ISSUE THREAD

**Issue by erigilg** [hackforla/product-management#152] opened 2021-03-04 23:57 UTC
### Overview
We need to create a guide for data analysis tools so that teams know the right tools to use for getting the desired results.

### Action Items
- [ ] Gather examples of how other projects have done, adding each example as a link in the resources section
   - [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)
    - [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label
- [ ] Create a guide on how to use the template 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources
Update issue #128 with the name of item you are working
Guide [url]

**Comment by ExperimentsInHonesty** [comment] 2021-12-06 16:38
@erigilg what was meant by Data Analysis tools?

We have the following guides that seem related.  
- https://github.com/hackforla/UI-UX/issues/60
- https://github.com/hackforla/product-management/issues/73 & - https://github.com/hackforla/product-management/issues/184 which seem to be about the same thing

**Comment by ExperimentsInHonesty** [comment] 2021-12-20 17:34
@erigilg Bumping this back up your inbox

> @erigilg what was meant by Data Analysis tools?
> 
> We have the following guides that seem related.
> 
> Create a Guide: Comparative & Competitive (C&C) Analysis UI-UX#60
> Create a Guide: Product Analytics Best Practices #73 & - Create a Guide/Template: Website analytics setup for your project #184 which seem to be about the same thing

**Comment by ExperimentsInHonesty** [comment] 2022-01-05 16:04
@erigilg we will reach out to you via slack today.

**Comment by ExperimentsInHonesty** [comment] 2022-03-18 15:10
I am closing this issue, because its a duplicate of other issues, see above

**Closed by ExperimentsInHonesty** 2022-03-18 15:10 UTC
Labels: documentation, TG: Gather Examples, feature: guide creation

**Comment by fchan218** [comment] 2024-10-26 17:59
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the Product Repo:</summary>
<p>

<img width="356" alt="Screenshot 2024-10-26 at 1 58 49 PM" src="https://github.com/user-attachments/assets/56c2fa89-15ac-418f-9891-f9fbb1b919e3">
</p>
</details>
